### PR TITLE
hw1_ions_stuff

### PR DESCRIPTION
**Pull request by Novaras**
- less time idling out of range (randomly)
- 2/3 as accurate vs vettes

### CODE REVIEW

**Comment by cloaked2222** [comment]
Whats secondaryTurnAngle do?

2/3 accuracy is still going to be way too strong. Try 1/3 as accurate (0.08 flat).
Then test: Spawn the frigs as p2 and corvs as p1, click fight, then spawn P1 hw1 resource controllers and have your missile vettes force attack them.
20 Kushan Ion Frigates vs 15 Missile Vette Squads attacking a resourcing operation = Target 400+ seconds for frigs to kill corvs.

**Comment by Novaras** [comment]
Do you also want this nerf for hgn ions?

**Comment by Novaras** [comment]
Data dump

|       | hmf         | kus ion 008 | tai ion 008 | hgn ion 024 | hgn ion 008 |
|-------|-------------|-------------|-------------|-------------|-------------|
|       | 398         | 350         | 348         | 180         | 301         |
|       | 402         | 362         | 332         | 191         | 316         |
|       | 412         | 340         | 359         | 184         | 311         |
|       | 399         | 341         | 345         | 194         | 305         |
|       | 401         | 314         | 344         | 190         | 299         |
|       | 427         | 304         | 343         | 200         | 330         |
|       | 390         | 365         | 332         | 178         | 307         |
|       | 378         | 380         | 318         | 182         | 301         |
|       | 396         | 362         | 351         | 179         | 300         |
|       | 392         | 365         | 363         | 195         | 298         |
| | | | |
| **Mean**  | 399.5       | 348.3       | 343.5       | 187.3       | 306.8       |
| **Range** | 49          | 76          | 45          | 22          | 32          |
| **SD**    | 13.10004241 | 24.04186164 | 13.39361374 | 7.703534542 | 9.975525606 |

**Comment by cloaked2222** [comment]
Good stuff. FYI, if its some non-important match-up like this a few tests is plenty.

Looks like ions will be better than HMF vs corvs in the distance. However HMF will be better than ions vs corvs swarming/attacking the frigates due to missiles vs fixed ions.

I'd go 0.06 for hiig ion frigs, then commit the changes.

**Comment by cloaked2222** [comment]
Whats secondaryTurnAngle do?

Also you didn't update the hiig ion .ship.

**Comment by Novaras** [comment]
Huh, actually not sure, I meant to remove that as it didn't seem to have a noticeable impact.

**Comment by cloaked2222** [comment]
Attack script changes are nice, but these should be applied too all frigs/caps in a separate pull.

I dropped it here:
File_Share\WIP\frontal_frigate.lua

**Pull request merged**
